name: TestFlight Upload

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Build Branch"
        required: true
        default: "develop"
      environment:
        description: "Select environment (staging or live)"
        required: true
        default: "staging"
      xcode_version:
        description: "Xcode version (16.4 or 26.3)"
        required: true
        default: "16.4"

jobs:
  notify-start:
    uses: ./.github/workflows/reusable-notify-start.yml
    with:
      message: "**[TESTFLIGHT UPLOAD STARTED]**\\nStarting TestFlight upload for branch **${{ github.event.inputs.branch }}**.\\nEnvironment: **${{ github.event.inputs.environment }}**.\\nPlease wait... :bicyclist: :man-biking: :woman-biking: :wind_blowing_face: "
    secrets: inherit

  ios-testflight:
    uses: ./.github/workflows/reusable-ios-testflight.yml
    with:
      branch: ${{ github.event.inputs.branch }}
      environment: ${{ github.event.inputs.environment }}
      xcode_version: ${{ github.event.inputs.xcode_version }}
    secrets: inherit
